python py1_DiffNormReads_per_CellType_per_Factor_MA.py
python py2_diff_logFC_per_CellType_compr_Factor_scatter.py
python py2b_diff_logFC_per_CellType_compr_Factor_scatter_k4me1_increased.py
python py3_diff_logFC_compr_CellType_per_Factor_scatter.py
python py3b_diff_logFC_compr_CellType_per_Factor_scatter_k4me1_increased.py
python py4_heatmap_across_CellTypes.py
python py4b_heatmap_across_CellTypes_k4me1_increased.py
